<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Geofence & Check-In Verification Settings
    |--------------------------------------------------------------------------
    |
    | Defines default radius in meters for GPS attendance verification,
    | time window buffers before and after shift start, and max client-server
    | clock drift tolerance.
    |
    */
    'geofence_default_radius' => env('VMS_GEOFENCE_RADIUS', 100), // meters
    'checkin_buffer_before'   => 15,  // minutes before shift start
    'checkin_buffer_after'    => 30,  // minutes after shift start
    'time_drift_tolerance'    => 2,   // minutes max allowed clock drift

    /*
    |--------------------------------------------------------------------------
    | Dynamic QR Code Security
    |--------------------------------------------------------------------------
    |
    | Expiration lifetime in minutes for cryptographically signed QR code
    | signatures generated by coordinators.
    |
    */
    'qr_expiry_minutes' => env('VMS_QR_EXPIRY_MINUTES', 15),

    /*
    |--------------------------------------------------------------------------
    | Certificate Issuance Milestones
    |--------------------------------------------------------------------------
    |
    | Thresholds of verified service hours that automatically trigger background
    | generation of official digital certificates.
    |
    */
    'certificate_milestones' => [10, 25, 50, 100, 200, 500],

    /*
    |--------------------------------------------------------------------------
    | Impact Score & Hours Metrics
    |--------------------------------------------------------------------------
    |
    | Rate of impact points earned per verified volunteer hour, and the cap limit.
    |
    */
    'impact_score_per_hour' => 0.10,
    'impact_score_max'      => 100.00,

    /*
    |--------------------------------------------------------------------------
    | AI Chatbot (VolunBot) Configuration
    |--------------------------------------------------------------------------
    |
    | Limits for session context history memory and rate limits.
    |
    */
    'chatbot_max_history' => 10,

    /*
    |--------------------------------------------------------------------------
    | System Pagination & Export Thresholds
    |--------------------------------------------------------------------------
    */
    'events_per_page' => 15,
    'report_per_page' => 50,

];
